const MAX_GALLERY_IMAGES_PER_PAGE = 6;

const MAX_REVIEWS_PER_PAGE = 10;

const MAX_NEARBY_OFFER_PER_PAGE = 3;

export {
  MAX_GALLERY_IMAGES_PER_PAGE,
  MAX_REVIEWS_PER_PAGE,
  MAX_NEARBY_OFFER_PER_PAGE,
};
